In [3]:
import pandas as pd
import numpy as np

In [4]:
utah_df = pd.read_csv('Smaller_Claim_Medical_Header.csv')

In [5]:
utah_df

,Claim_ID,Claim_Type_Cd,Claim_Type_Desc,Admit_Type_Cd,Admit_Type_Desc,Admit_Source_Cd,Admit_Source_Desc,Discharge_Status_Cd,Discharge_Status_Desc,Bill_Type_Cd,...,Member_Age_Years,Length_of_Stay,ER_Flag,Line_Count,Deductible_Amt,Dental_Flag,Service_Start_Year,Small_Area_Cd,Gender_Cd,Member_Gender_Desc
0,248134065,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,51,0.0,N,3,0.00,N,2016,4.0,F,Female
1,186070247,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,51,0.0,N,1,0.00,N,2016,60.0,M,Male
2,249716086,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,4,0.0,N,1,0.00,N,2016,13.0,M,Male
3,248618084,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,61,0.0,N,3,0.00,N,2016,34.1,M,Male
4,278512556,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,54,0.0,N,1,0.00,N,2016,26.0,F,Female
5,279908505,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,58,0.0,N,5,0.00,N,2016,57.0,F,Female
6,279949652,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,5,0.0,N,1,0.00,N,2016,9.0,M,Male
7,249303559,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,45,0.0,N,1,0.00,N,2016,57.0,F,Female
8,281084958,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,25,0.0,N,1,0.00,N,2016,39.0,F,Female
9,238230063,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,22,0.0,N,2,0.00,N,2016,12.0,F,Female
10,280740659,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,23,0.0,N,1,0.00,N,2016,5.0,F,Female
11,283235494,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,8,0.0,N,1,0.00,N,2016,49.0,F,Female
12,249554668,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,52,0.0,N,3,0.00,N,2016,37.0,F,Female
13,247844821,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,69,0.0,N,1,0.00,N,2016,47.0,F,Female
14,279034248,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,27,0.0,N,1,108.12,N,2016,24.0,F,Female
15,278397119,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,1,0.0,N,2,0.00,N,2016,23.1,F,Female
16,249743540,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,77,0.0,N,1,0.00,N,2016,21.0,F,Female
17,282434904,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,47,0.0,N,1,0.00,N,2016,29.1,F,Female
18,282501158,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,34,0.0,N,2,0.00,N,2016,9.0,F,Female
19,278369731,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,37,0.0,N,6,81.02,N,2016,42.0,F,Female
20,279646274,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,42,0.0,N,3,0.00,N,2016,7.0,F,Female
21,278579514,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,36,0.0,N,1,0.00,N,2016,14.0,F,Female
22,283211595,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,15,0.0,N,1,0.00,N,2016,21.0,F,Female
23,238371455,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,58,0.0,N,3,0.00,N,2016,48.0,F,Female
24,278941300,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,1,0.0,N,1,0.00,N,2016,35.0,M,Male
25,278447986,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,45,0.0,N,1,0.00,N,2016,10.0,F,Female
26,279152584,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,28,0.0,N,1,0.00,N,2016,7.0,F,Female
27,171410216,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,5,0.0,N,1,0.00,N,2016,27.0,F,Female
28,248865143,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,33,0.0,N,3,0.00,Y,2016,32.0,M,Male
29,279344691,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,32,0.0,N,1,0.00,N,2016,50.0,F,Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99969,109068390,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,26,1.0,Y,8,0.00,N,2016,26.0,F,Female
99970,109068392,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,64,0.0,Y,16,0.00,N,2016,25.0,M,Male
99971,109068395,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,11,0.0,Y,5,0.00,N,2016,30.1,M,Male
99972,109068404,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,58,0.0,Y,3,0.00,N,2016,NaN,M,Male
99973,109068407,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,66,0.0,Y,16,0.00,N,2016,20.0,F,Female
99974,109068410,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,37,0.0,N,2,3.00,N,2016,34.1,F,Female
99975,109068413,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,29,0.0,Y,14,6.00,N,2016,20.0,F,Female
99976,109068415,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,29,0.0,N,9,3.00,N,2016,27.0,F,Female
99977,109068420,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,12,0.0,Y,16,0.00,N,2016,25.0,F,Female
99978,109068422,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,43,0.0,N,3,0.00,N,2016,30.1,M,Male
99979,109068424,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,78,0.0,N,4,0.00,N,2016,23.1,F,Female
99980,109068428,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,36,1.0,Y,14,6.00,N,2016,30.1,F,Female
99981,109068429,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,65,0.0,N,1,0.00,N,2016,17.0,F,Female
99982,109068431,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,58,0.0,Y,16,6.00,N,2016,25.0,F,Female
99983,109068438,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,29,0.0,Y,6,6.00,N,2016,27.0,M,Male
99984,109068441,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,46,0.0,N,3,3.00,N,2016,32.0,F,Female
99985,109068446,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,43,0.0,N,2,3.00,N,2016,34.2,F,Female
99986,109068448,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,0,0.0,Y,3,0.00,N,2016,NaN,F,Female
99987,109068451,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,51,0.0,N,2,3.00,N,2016,26.0,M,Male
99988,109068452,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,78,0.0,N,2,0.00,N,2016,24.0,F,Female
99989,109068455,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,19,0.0,N,1,0.00,N,2016,20.0,F,Female
99990,109068460,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,37,0.0,Y,1,0.00,N,2016,32.0,F,Female
99991,109068467,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,41,0.0,Y,1,6.00,N,2016,NaN,M,Male
99992,109068469,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,21,0.0,Y,2,0.00,N,2016,27.0,F,Female
99993,109068474,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,48,0.0,N,1,0.00,N,2016,24.0,M,Male
99994,109068487,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,1,0.0,Y,2,0.00,N,2016,26.0,M,Male
99995,109068506,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,39,0.0,Y,11,6.00,N,2016,28.0,F,Female
99996,109068510,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,69,0.0,Y,2,0.00,N,2016,30.0,F,Female
99997,109068511,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,9,0.0,Y,3,0.00,N,2016,5.0,M,Male
99998,109068513,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,65,0.0,Y,8,0.00,N,2016,17.0,F,Female

In [8]:
len(utah_df.columns)

34

In [10]:
utah_df['Claim_Type_Cd'].nunique()

3

In [36]:
utah_df['Admission_Dx_ID'].nunique()

2945

In [42]:
utah_df['Bill_Type_Cd'].nunique()

61

In [30]:
#Get rid of nonnumeric or descriptive columns 
utah_df1 = utah_df.drop(['Dental_Flag', 'Service_Start_Year', 'Third_Party_Liability_Desc', 'Member_Gender_Desc', 'Discharge_Status_Desc', 'Admit_Source_Desc', 'Admit_Type_Desc', 'Claim_Type_Cd', 'Units_of'], axis=1)
utah_df1

,Claim_ID,Claim_Type_Desc,Admit_Type_Cd,Admit_Source_Cd,Discharge_Status_Cd,Bill_Type_Cd,Third_Party_Liability_Cd,E_Cd,Service_Start_Dt,Charge_Amt,...,Admission_Dx_ID,Principal_Dx_ID,Primary_Proc_ID,Member_Age_Years,Length_of_Stay,ER_Flag,Line_Count,Deductible_Amt,Small_Area_Cd,Gender_Cd
0,248134065,Professional,9,9,0,UK,1,NaN,2016-02-23,320.00,...,9999999,3086,9999999,51,0.0,N,3,0.00,4.0,F
1,186070247,Professional,9,9,0,UK,1,NaN,2016-04-22,150.00,...,9999999,4775,9999999,51,0.0,N,1,0.00,60.0,M
2,249716086,Professional,9,9,0,UK,1,NaN,2016-12-19,141.39,...,9999999,9248,9999999,4,0.0,N,1,0.00,13.0,M
3,248618084,Professional,9,9,0,UK,1,NaN,2016-06-08,385.00,...,9999999,2789,9999999,61,0.0,N,3,0.00,34.1,M
4,278512556,Professional,9,9,0,UK,1,NaN,2016-02-02,60.00,...,9999999,9401,9999999,54,0.0,N,1,0.00,26.0,F
5,279908505,Outpatient,9,9,0,131,1,NaN,2016-04-27,392.00,...,9999999,21816,9999999,58,0.0,N,5,0.00,57.0,F
6,279949652,Professional,9,9,0,UK,1,NaN,2016-04-28,237.00,...,9999999,22496,9999999,5,0.0,N,1,0.00,9.0,M
7,249303559,Professional,9,9,0,UK,1,NaN,2016-10-11,61.25,...,9999999,17289,9999999,45,0.0,N,1,0.00,57.0,F
8,281084958,Professional,9,9,0,UK,1,NaN,2016-07-26,10.00,...,9999999,68912,9999999,25,0.0,N,1,0.00,39.0,F
9,238230063,Professional,9,9,0,UK,1,NaN,2016-04-04,473.00,...,9999999,20057,9999999,22,0.0,N,2,0.00,12.0,F
10,280740659,Professional,9,9,0,UK,1,NaN,2016-06-16,72.82,...,9999999,68734,9999999,23,0.0,N,1,0.00,5.0,F
11,283235494,Professional,9,9,0,UK,1,NaN,2016-12-15,11.66,...,9999999,9250,9999999,8,0.0,N,1,0.00,49.0,F
12,249554668,Professional,9,9,0,UK,1,NaN,2016-11-21,174.00,...,9999999,13907,9999999,52,0.0,N,3,0.00,37.0,F
13,247844821,Professional,9,9,0,UK,1,NaN,2016-01-16,289.30,...,9999999,21373,9999999,69,0.0,N,1,0.00,47.0,F
14,279034248,Professional,9,9,0,UK,1,NaN,2016-02-24,110.00,...,9999999,4130,9999999,27,0.0,N,1,108.12,24.0,F
15,278397119,Outpatient,9,9,0,131,1,NaN,2016-01-19,89.97,...,9999999,68768,9999999,1,0.0,N,2,0.00,23.1,F
16,249743540,Professional,9,9,0,UK,1,NaN,2016-12-21,760.48,...,9999999,21373,9999999,77,0.0,N,1,0.00,21.0,F
17,282434904,Professional,9,9,0,UK,1,NaN,2016-09-26,176.00,...,9999999,9246,9999999,47,0.0,N,1,0.00,29.1,F
18,282501158,Professional,9,9,0,UK,1,NaN,2016-10-21,240.00,...,9999999,68848,9999999,34,0.0,N,2,0.00,9.0,F
19,278369731,Professional,9,9,0,UK,1,NaN,2016-01-21,733.00,...,9999999,2931,9999999,37,0.0,N,6,81.02,42.0,F
20,279646274,Professional,9,9,0,UK,1,NaN,2016-04-08,288.00,...,9999999,17830,9999999,42,0.0,N,3,0.00,7.0,F
21,278579514,Professional,9,9,0,UK,1,NaN,2016-01-22,150.00,...,9999999,10659,9999999,36,0.0,N,1,0.00,14.0,F
22,283211595,Professional,9,9,0,UK,1,NaN,2016-12-13,22.20,...,9999999,21519,9999999,15,0.0,N,1,0.00,21.0,F
23,238371455,Professional,9,9,0,UK,1,NaN,2016-05-24,204.70,...,9999999,68646,9999999,58,0.0,N,3,0.00,48.0,F
24,278941300,Professional,9,9,0,UK,1,NaN,2016-02-29,120.00,...,9999999,9267,9999999,1,0.0,N,1,0.00,35.0,M
25,278447986,Professional,9,9,0,UK,1,NaN,2016-01-06,504.00,...,9999999,10711,9999999,45,0.0,N,1,0.00,10.0,F
26,279152584,Professional,9,9,0,UK,1,NaN,2016-01-11,196.50,...,9999999,18185,9999999,28,0.0,N,1,0.00,7.0,F
27,171410216,Professional,9,9,0,UK,1,NaN,2016-06-18,499.85,...,9999999,22529,9999999,5,0.0,N,1,0.00,27.0,F
28,248865143,Professional,9,9,0,UK,1,NaN,2016-07-14,211.00,...,9999999,68665,9999999,33,0.0,N,3,0.00,32.0,M
29,279344691,Professional,9,9,0,UK,1,NaN,2016-03-15,3574.00,...,9999999,19830,9999999,32,0.0,N,1,0.00,50.0,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99969,109068390,Outpatient,9,9,0,131,1,NaN,2016-02-21,3557.40,...,9999999,21407,9999999,26,1.0,Y,8,0.00,26.0,F
99970,109068392,Outpatient,9,9,0,131,1,NaN,2016-02-23,9954.99,...,9999999,734,9999999,64,0.0,Y,16,0.00,25.0,M
99971,109068395,Outpatient,9,9,0,131,1,NaN,2016-02-23,1440.72,...,9999999,734,9999999,11,0.0,Y,5,0.00,30.1,M
99972,109068404,Outpatient,9,9,0,131,1,W260XXA,2016-02-25,1535.42,...,9999999,36548,9999999,58,0.0,Y,3,0.00,NaN,M
99973,109068407,Outpatient,9,9,0,131,1,NaN,2016-02-24,6026.15,...,9999999,21370,9999999,66,0.0,Y,16,0.00,20.0,F
99974,109068410,Outpatient,9,9,0,131,1,NaN,2016-02-22,4167.24,...,9999999,21371,9999999,37,0.0,N,2,3.00,34.1,F
99975,109068413,Outpatient,9,9,0,131,1,NaN,2016-02-24,5157.10,...,9999999,4038,9999999,29,0.0,Y,14,6.00,20.0,F
99976,109068415,Outpatient,9,9,0,131,1,NaN,2016-02-24,11276.02,...,9999999,10673,9999999,29,0.0,N,9,3.00,27.0,F
99977,109068420,Outpatient,9,9,0,131,1,NaN,2016-02-26,5279.33,...,9999999,9267,9999999,12,0.0,Y,16,0.00,25.0,F
99978,109068422,Outpatient,9,9,0,131,1,NaN,2016-02-22,1121.71,...,9999999,1099,9999999,43,0.0,N,3,0.00,30.1,M
99979,109068424,Outpatient,9,9,0,131,1,W19XXXA,2016-02-04,756.99,...,9999999,8014,9999999,78,0.0,N,4,0.00,23.1,F
99980,109068428,Outpatient,9,9,0,131,1,NaN,2016-02-24,4437.13,...,9999999,734,9999999,36,1.0,Y,14,6.00,30.1,F
99981,109068429,Outpatient,9,9,0,131,1,NaN,2016-03-02,138.97,...,9999999,3430,9999999,65,0.0,N,1,0.00,17.0,F
99982,109068431,Outpatient,9,9,0,131,1,NaN,2016-02-24,4764.09,...,9999999,56665,9999999,58,0.0,Y,16,6.00,25.0,F
99983,109068438,Outpatient,9,9,0,131,1,NaN,2016-03-10,1706.30,...,9999999,9275,9999999,29,0.0,Y,6,6.00,27.0,M
99984,109068441,Outpatient,9,9,0,131,1,NaN,2016-03-10,835.97,...,9999999,17741,9999999,46,0.0,N,3,3.00,32.0,F
99985,109068446,Outpatient,9,9,0,131,1,NaN,2016-03-10,518.03,...,9999999,68732,9999999,43,0.0,N,2,3.00,34.2,F
99986,109068448,Outpatient,9,9,0,131,1,NaN,2016-03-10,1727.63,...,9999999,9267,9999999,0,0.0,Y,3,0.00,NaN,F
99987,109068451,Outpatient,9,9,0,131,1,NaN,2016-03-09,2245.40,...,9999999,2549,9999999,51,0.0,N,2,3.00,26.0,M
99988,109068452,Outpatient,9,9,0,131,1,NaN,2016-01-06,238.02,...,9999999,17538,9999999,78,0.0,N,2,0.00,24.0,F
99989,109068455,Outpatient,9,9,0,131,1,NaN,2016-03-09,420.26,...,9999999,68918,9999999,19,0.0,N,1,0.00,20.0,F
99990,109068460,Outpatient,9,9,0,131,1,NaN,2016-03-10,736.63,...,9999999,3679,9999999,37,0.0,Y,1,0.00,32.0,F
99991,109068467,Outpatient,9,9,0,131,1,NaN,2016-03-10,1212.93,...,9999999,21726,9999999,41,0.0,Y,1,6.00,NaN,M
99992,109068469,Outpatient,9,9,0,131,1,NaN,2016-03-10,2039.66,...,9999999,7443,9999999,21,0.0,Y,2,0.00,27.0,F
99993,109068474,Outpatient,9,9,0,131,1,NaN,2016-03-09,388.90,...,9999999,21349,9999999,48,0.0,N,1,0.00,24.0,M
99994,109068487,Outpatient,9,9,0,131,1,NaN,2016-02-12,772.89,...,9999999,9267,9999999,1,0.0,Y,2,0.00,26.0,M
99995,109068506,Outpatient,9,9,0,131,1,NaN,2016-03-10,6424.62,...,9999999,21726,9999999,39,0.0,Y,11,6.00,28.0,F
99996,109068510,Outpatient,9,9,0,131,1,W010XXA,2016-03-10,2529.55,...,9999999,24776,9999999,69,0.0,Y,2,0.00,30.0,F
99997,109068511,Outpatient,9,9,0,131,1,Y9366,2016-03-10,1697.82,...,9999999,13153,9999999,9,0.0,Y,3,0.00,5.0,M
99998,109068513,Outpatient,9,9,0,131,1,NaN,2016-02-29,3861.09,...,9999999,21415,9999999,65,0.0,Y,8,0.00,17.0,F

In [32]:
len(utah_df1.columns)

26

In [38]:
list(utah_df1.columns.values)

['Claim_ID',
 'Claim_Type_Desc',
 'Admit_Type_Cd',
 'Admit_Source_Cd',
 'Discharge_Status_Cd',
 'Bill_Type_Cd',
 'Third_Party_Liability_Cd',
 'E_Cd',
 'Service_Start_Dt',
 'Charge_Amt',
 'Plan_Paid_Amt',
 'Prepaid_Amt',
 'Copay_Amt',
 'Coinsurance_Amt',
 'Line_of_Business_Cd',
 'Capitation_Flag',
 'Admission_Dx_ID',
 'Principal_Dx_ID',
 'Primary_Proc_ID',
 'Member_Age_Years',
 'Length_of_Stay',
 'ER_Flag',
 'Line_Count',
 'Deductible_Amt',
 'Small_Area_Cd',
 'Gender_Cd']

In [39]:
utah_df1['Charge_Amt']

0          320.00
1          150.00
2          141.39
3          385.00
4           60.00
5          392.00
6          237.00
7           61.25
8           10.00
9          473.00
10          72.82
11          11.66
12         174.00
13         289.30
14         110.00
15          89.97
16         760.48
17         176.00
18         240.00
19         733.00
20         288.00
21         150.00
22          22.20
23         204.70
24         120.00
25         504.00
26         196.50
27         499.85
28         211.00
29        3574.00
           ...
99969     3557.40
99970     9954.99
99971     1440.72
99972     1535.42
99973     6026.15
99974     4167.24
99975     5157.10
99976    11276.02
99977     5279.33
99978     1121.71
99979      756.99
99980     4437.13
99981      138.97
99982     4764.09
99983     1706.30
99984      835.97
99985      518.03
99986     1727.63
99987     2245.40
99988      238.02
99989      420.26
99990      736.63
99991     1212.93
99992     2039.66
99993      388.90
99994      772.89
99995     6424.62
99996     2529.55
99997     1697.82
99998     3861.09
Name: Charge_Amt, Length: 99999, dtype: float64

In [40]:
utah_df1[['Claim_ID', 'Charge_Amt']]

        Claim_ID  Charge_Amt
0      248134065      320.00
1      186070247      150.00
2      249716086      141.39
3      248618084      385.00
4      278512556       60.00
5      279908505      392.00
6      279949652      237.00
7      249303559       61.25
8      281084958       10.00
9      238230063      473.00
10     280740659       72.82
11     283235494       11.66
12     249554668      174.00
13     247844821      289.30
14     279034248      110.00
15     278397119       89.97
16     249743540      760.48
17     282434904      176.00
18     282501158      240.00
19     278369731      733.00
20     279646274      288.00
21     278579514      150.00
22     283211595       22.20
23     238371455      204.70
24     278941300      120.00
25     278447986      504.00
26     279152584      196.50
27     171410216      499.85
28     248865143      211.00
29     279344691     3574.00
...          ...         ...
99969  109068390     3557.40
99970  109068392     9954.99
99971  109068395     1440.72
99972  109068404     1535.42
99973  109068407     6026.15
99974  109068410     4167.24
99975  109068413     5157.10
99976  109068415    11276.02
99977  109068420     5279.33
99978  109068422     1121.71
99979  109068424      756.99
99980  109068428     4437.13
99981  109068429      138.97
99982  109068431     4764.09
99983  109068438     1706.30
99984  109068441      835.97
99985  109068446      518.03
99986  109068448     1727.63
99987  109068451     2245.40
99988  109068452      238.02
99989  109068455      420.26
99990  109068460      736.63
99991  109068467     1212.93
99992  109068469     2039.66
99993  109068474      388.90
99994  109068487      772.89
99995  109068506     6424.62
99996  109068510     2529.55
99997  109068511     1697.82
99998  109068513     3861.09

[99999 rows x 2 columns]

In [41]:
utah_df1.isnull().sum(axis = 0)

Claim_ID                        0
Claim_Type_Desc                 0
Admit_Type_Cd                   0
Admit_Source_Cd                 0
Discharge_Status_Cd             0
Bill_Type_Cd                    0
Third_Party_Liability_Cd        0
E_Cd                        95642
Service_Start_Dt                0
Charge_Amt                      0
Plan_Paid_Amt                   0
Prepaid_Amt                     0
Copay_Amt                       0
Coinsurance_Amt                 0
Line_of_Business_Cd             0
Capitation_Flag                 0
Admission_Dx_ID                 0
Principal_Dx_ID                 0
Primary_Proc_ID                 0
Member_Age_Years                0
Length_of_Stay                  0
ER_Flag                         0
Line_Count                      0
Deductible_Amt                  0
Small_Area_Cd                9934
Gender_Cd                       0
dtype: int64