In [3]:
import pandas as pd
import numpy as np

In [4]:
utah_df = pd.read_csv('Smaller_Claim_Medical_Header.csv')

In [5]:
utah_df

,Claim_ID,Claim_Type_Cd,Claim_Type_Desc,Admit_Type_Cd,Admit_Type_Desc,Admit_Source_Cd,Admit_Source_Desc,Discharge_Status_Cd,Discharge_Status_Desc,Bill_Type_Cd,...,Member_Age_Years,Length_of_Stay,ER_Flag,Line_Count,Deductible_Amt,Dental_Flag,Service_Start_Year,Small_Area_Cd,Gender_Cd,Member_Gender_Desc
0,248134065,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,51,0.0,N,3,0.00,N,2016,4.0,F,Female
1,186070247,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,51,0.0,N,1,0.00,N,2016,60.0,M,Male
2,249716086,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,4,0.0,N,1,0.00,N,2016,13.0,M,Male
3,248618084,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,61,0.0,N,3,0.00,N,2016,34.1,M,Male
4,278512556,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,54,0.0,N,1,0.00,N,2016,26.0,F,Female
5,279908505,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,58,0.0,N,5,0.00,N,2016,57.0,F,Female
6,279949652,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,5,0.0,N,1,0.00,N,2016,9.0,M,Male
7,249303559,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,45,0.0,N,1,0.00,N,2016,57.0,F,Female
8,281084958,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,25,0.0,N,1,0.00,N,2016,39.0,F,Female
9,238230063,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,22,0.0,N,2,0.00,N,2016,12.0,F,Female
10,280740659,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,23,0.0,N,1,0.00,N,2016,5.0,F,Female
11,283235494,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,8,0.0,N,1,0.00,N,2016,49.0,F,Female
12,249554668,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,52,0.0,N,3,0.00,N,2016,37.0,F,Female
13,247844821,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,69,0.0,N,1,0.00,N,2016,47.0,F,Female
14,279034248,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,27,0.0,N,1,108.12,N,2016,24.0,F,Female
15,278397119,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,1,0.0,N,2,0.00,N,2016,23.1,F,Female
16,249743540,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,77,0.0,N,1,0.00,N,2016,21.0,F,Female
17,282434904,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,47,0.0,N,1,0.00,N,2016,29.1,F,Female
18,282501158,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,34,0.0,N,2,0.00,N,2016,9.0,F,Female
19,278369731,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,37,0.0,N,6,81.02,N,2016,42.0,F,Female
20,279646274,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,42,0.0,N,3,0.00,N,2016,7.0,F,Female
21,278579514,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,36,0.0,N,1,0.00,N,2016,14.0,F,Female
22,283211595,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,15,0.0,N,1,0.00,N,2016,21.0,F,Female
23,238371455,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,58,0.0,N,3,0.00,N,2016,48.0,F,Female
24,278941300,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,1,0.0,N,1,0.00,N,2016,35.0,M,Male
25,278447986,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,45,0.0,N,1,0.00,N,2016,10.0,F,Female
26,279152584,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,28,0.0,N,1,0.00,N,2016,7.0,F,Female
27,171410216,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,5,0.0,N,1,0.00,N,2016,27.0,F,Female
28,248865143,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,33,0.0,N,3,0.00,Y,2016,32.0,M,Male
29,279344691,P,Professional,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,UK,...,32,0.0,N,1,0.00,N,2016,50.0,F,Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99969,109068390,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,26,1.0,Y,8,0.00,N,2016,26.0,F,Female
99970,109068392,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,64,0.0,Y,16,0.00,N,2016,25.0,M,Male
99971,109068395,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,11,0.0,Y,5,0.00,N,2016,30.1,M,Male
99972,109068404,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,58,0.0,Y,3,0.00,N,2016,NaN,M,Male
99973,109068407,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,66,0.0,Y,16,0.00,N,2016,20.0,F,Female
99974,109068410,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,37,0.0,N,2,3.00,N,2016,34.1,F,Female
99975,109068413,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,29,0.0,Y,14,6.00,N,2016,20.0,F,Female
99976,109068415,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,29,0.0,N,9,3.00,N,2016,27.0,F,Female
99977,109068420,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,12,0.0,Y,16,0.00,N,2016,25.0,F,Female
99978,109068422,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,43,0.0,N,3,0.00,N,2016,30.1,M,Male
99979,109068424,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,78,0.0,N,4,0.00,N,2016,23.1,F,Female
99980,109068428,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,36,1.0,Y,14,6.00,N,2016,30.1,F,Female
99981,109068429,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,65,0.0,N,1,0.00,N,2016,17.0,F,Female
99982,109068431,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,58,0.0,Y,16,6.00,N,2016,25.0,F,Female
99983,109068438,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,29,0.0,Y,6,6.00,N,2016,27.0,M,Male
99984,109068441,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,46,0.0,N,3,3.00,N,2016,32.0,F,Female
99985,109068446,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,43,0.0,N,2,3.00,N,2016,34.2,F,Female
99986,109068448,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,0,0.0,Y,3,0.00,N,2016,NaN,F,Female
99987,109068451,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,51,0.0,N,2,3.00,N,2016,26.0,M,Male
99988,109068452,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,78,0.0,N,2,0.00,N,2016,24.0,F,Female
99989,109068455,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,19,0.0,N,1,0.00,N,2016,20.0,F,Female
99990,109068460,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,37,0.0,Y,1,0.00,N,2016,32.0,F,Female
99991,109068467,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,41,0.0,Y,1,6.00,N,2016,NaN,M,Male
99992,109068469,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,21,0.0,Y,2,0.00,N,2016,27.0,F,Female
99993,109068474,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,48,0.0,N,1,0.00,N,2016,24.0,M,Male
99994,109068487,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,1,0.0,Y,2,0.00,N,2016,26.0,M,Male
99995,109068506,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,39,0.0,Y,11,6.00,N,2016,28.0,F,Female
99996,109068510,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,69,0.0,Y,2,0.00,N,2016,30.0,F,Female
99997,109068511,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,9,0.0,Y,3,0.00,N,2016,5.0,M,Male
99998,109068513,O,Outpatient,9,INFORMATION NOT AVAILABLE,9,Information Not Available,0,Unknown,131,...,65,0.0,Y,8,0.00,N,2016,17.0,F,Female

In [6]:
medical_line_df = pd.read_csv('Smaller_Claim_Medical_Line.csv')

In [7]:
medical_line_df

,Claim_ID,Claim_Line_No,Place_of_Service_Cd,Rev_Cd,CPT4_ID,CPT4_Mod1_Cd,CPT4_Mod2_Cd,CPT4_Mod3_Cd,CPT4_Mod4_Cd,Service_Start_Dt,...,NDC_Cd,Capitation_Flag,ER_Flag,Copay_Amt,Coinsurance_Amt,Deductible_Amt,Dental_Flag,Unit_Of_Measure_Cd,Unit_Of_Measure_Desc,Service_Start_Year
0,358985506,19,11,NaN,D9951,,,,,2016-10-05,...,0,N,N,0.00,0.00,0.00,Y,UN,Units,2016
1,358982958,3,11,NaN,D0120,,,,,2016-02-02,...,0,N,N,0.00,0.00,28.00,Y,UN,Units,2016
2,238253746,1,11,NaN,99213,25,,,,2016-04-25,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
3,358996411,3,11,NaN,96372,,,,,2016-04-05,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
4,358985561,2,11,NaN,17280,XU,,,,2016-12-22,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
5,358984479,1,99,450.0,00000,,,,,2016-02-13,...,0,N,Y,0.00,0.00,281.00,N,UN,Units,2016
6,171447849,1,11,NaN,99213,,,,,2016-07-26,...,0,N,N,0.00,7.45,0.00,N,UN,Units,2016
7,358987119,24,99,444.0,00000,,,,,2016-04-28,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
8,358996654,32,99,551.0,00000,,,,,2016-09-30,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
9,281568939,1,23,NaN,99284,,,,,2016-08-23,...,0,N,N,0.00,0.00,441.35,N,UN,Units,2016
10,239303210,1,11,NaN,D4910,,,,,2016-12-29,...,0,N,N,0.00,15.31,0.00,Y,UN,Units,2016
11,248413959,1,11,NaN,97110,GP,,,,2016-04-12,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
12,358995481,9,99,551.0,00000,,,,,2016-12-30,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
13,248413959,2,11,NaN,97140,59,GP,,,2016-04-12,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
14,358983710,3,11,NaN,D2392,,,,,2016-06-21,...,0,N,N,0.00,14.30,50.00,Y,UN,Units,2016
15,358952520,1,11,NaN,D4341,,,,,2016-06-01,...,0,N,N,0.00,66.50,0.00,Y,UN,Units,2016
16,358952568,6,99,304.0,00000,,,,,2016-04-04,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
17,358950309,9,99,301.0,00000,,,,,2016-04-16,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
18,359004724,9,99,301.0,00000,,,,,2016-12-21,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
19,359002401,20,99,851.0,00000,,,,,2016-06-13,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
20,359005061,2,99,200.0,00000,,,,,2016-02-29,...,0,N,N,92.81,0.00,0.00,N,UN,Units,2016
21,359002695,6,11,NaN,D9223,,,,,2016-11-22,...,0,N,N,0.00,18.00,0.00,Y,UN,Units,2016
22,359005076,2,11,NaN,96372,,,,,2016-10-25,...,0,N,N,0.00,0.00,27.48,N,UN,Units,2016
23,359005181,2,99,270.0,00000,,,,,2016-11-10,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
24,359002843,17,99,636.0,00000,,,,,2016-01-29,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
25,171447851,1,11,NaN,99393,,,,,2016-08-03,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
26,282610850,1,11,NaN,99214,,,,,2016-11-01,...,0,N,N,30.00,0.00,0.00,N,UN,Units,2016
27,358956207,3,11,NaN,D0272,,,,,2016-09-26,...,0,N,N,0.00,0.00,0.00,Y,UN,Units,2016
28,283264429,1,11,NaN,99205,,,,,2016-12-09,...,0,N,N,3.00,0.00,0.00,N,UN,Units,2016
29,281568959,1,11,NaN,99215,,,,,2016-08-25,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99969,171173858,2,11,NaN,93005,,,,,2016-02-18,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
99970,171173859,1,11,NaN,99214,,,,,2016-02-18,...,0,N,N,45.00,0.00,0.00,N,UN,Units,2016
99971,171173859,2,11,NaN,71020,,,,,2016-02-18,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
99972,171173872,2,22,NaN,31256,LT,,,,2016-02-08,...,0,N,N,0.00,34.49,0.00,N,UN,Units,2016
99973,171173872,3,22,NaN,31240,RT,,,,2016-02-08,...,0,N,N,0.00,27.97,0.00,N,UN,Units,2016
99974,171173872,4,22,NaN,31240,LT,,,,2016-02-08,...,0,N,N,0.00,27.97,0.00,N,UN,Units,2016
99975,171173873,1,11,NaN,99214,,,,,2016-02-17,...,0,N,N,30.00,0.00,0.00,N,UN,Units,2016
99976,171173874,1,11,NaN,99214,,,,,2016-02-17,...,0,N,N,20.00,0.00,0.00,N,UN,Units,2016
99977,171173875,1,11,NaN,99214,,,,,2016-02-17,...,0,N,N,0.00,0.00,130.09,N,UN,Units,2016
99978,171173876,1,11,NaN,99391,25,,,,2016-02-19,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
99979,171173876,2,11,NaN,90473,,,,,2016-02-19,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
99980,171173876,3,11,NaN,90472,,,,,2016-02-19,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
99981,171173876,4,11,NaN,90685,,,,,2016-02-19,...,49281051525,N,N,0.00,0.00,0.00,N,UN,Units,2016
99982,171173876,5,11,NaN,90670,,,,,2016-02-19,...,5197101,N,N,0.00,0.00,0.00,N,UN,Units,2016
99983,171173876,6,11,NaN,90680,,,,,2016-02-19,...,6404741,N,N,0.00,0.00,0.00,N,UN,Units,2016
99984,171173876,7,11,NaN,90723,,,,,2016-02-19,...,58160081143,N,N,0.00,0.00,0.00,N,UN,Units,2016
99985,171173877,1,11,NaN,99213,,,,,2016-02-18,...,0,N,N,20.00,0.00,0.00,N,UN,Units,2016
99986,171173878,1,11,NaN,99214,,,,,2016-02-18,...,0,N,N,25.00,0.00,0.00,N,UN,Units,2016
99987,171173879,1,11,NaN,99203,,,,,2016-02-17,...,0,N,N,30.00,0.00,0.00,N,UN,Units,2016
99988,171173880,1,11,NaN,99391,25,,,,2016-02-16,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
99989,171173880,2,11,NaN,90471,,,,,2016-02-16,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
99990,171173880,3,11,NaN,90472,,,,,2016-02-16,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
99991,171173880,4,11,NaN,90474,,,,,2016-02-16,...,0,N,N,0.00,0.00,0.00,N,UN,Units,2016
99992,171173880,5,11,NaN,90648,,,,,2016-02-16,...,49281054505,N,N,0.00,0.00,0.00,N,UN,Units,2016
99993,171173880,6,11,NaN,90723,,,,,2016-02-16,...,58160081152,N,N,0.00,0.00,0.00,N,UN,Units,2016
99994,171173881,1,11,NaN,90670,,,,,2016-02-16,...,5197102,N,N,0.00,0.00,0.00,N,UN,Units,2016
99995,171173881,2,11,NaN,90680,,,,,2016-02-16,...,6404741,N,N,0.00,0.00,0.00,N,UN,Units,2016
99996,171173882,1,21,NaN,99223,,,,,2016-02-17,...,0,N,N,0.00,0.00,252.96,N,UN,Units,2016
99997,171173883,1,21,NaN,99239,,,,,2016-02-18,...,0,N,N,0.00,0.00,131.52,N,UN,Units,2016
99998,347919445,5,99,NaN,D2391,,,,,2016-08-23,...,0,N,N,0.00,19.20,0.00,Y,UN,Units,2016